sudo: false
language: node_js
node_js:
  - "7"
  - "6"
script:
- npm run lint
- npm run test:cover
- npm run build
after_success:
- npm run coveralls
before_deploy:
- cd dist
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: "./app-engine-key.json"
  project: dar-tool-api
  on:
    branch: master
    node: "7"
before_install:
- openssl aes-256-cbc -K $encrypted_850c096954d4_key -iv $encrypted_850c096954d4_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
